//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    
    public partial class BuscarServicio_Result1
    {
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Observaciones { get; set; }
        public double ValorUnitario { get; set; }
        public string Tabla { get; set; }
    }
}
