//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.OrdenServicio = new HashSet<OrdenServicio>();
        }
    
        public string CedulaEmpleado { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechadeNacimiento { get; set; }
        public string Cargo { get; set; }
        public System.DateTime FechadeIngreso { get; set; }
        public string Disponibilidad { get; set; }
        public Nullable<System.DateTime> FechadeRetiro { get; set; }
        public string Observaciones { get; set; }
        public string Estado { get; set; }
        public string Contrato { get; set; }
        public Nullable<double> Salario { get; set; }
        public string Eps { get; set; }
        public string CajaCompensaciones { get; set; }
        public string Pensiones { get; set; }
        public string ARP { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<OrdenServicio> OrdenServicio { get; set; }
    }
}
