//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int NumeroFactura { get; set; }
        public int NumeroOrdSer { get; set; }
        public string CCNit { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string Observaciones { get; set; }
        public double Subtotal { get; set; }
        public double ValorIva { get; set; }
        public double Impuestos { get; set; }
        public double Descuento { get; set; }
        public double ValorTotal { get; set; }
        public string Usuario { get; set; }
        public string Estado { get; set; }
        public Nullable<int> NumeroRemision { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual OrdenServicio OrdenServicio { get; set; }
        public virtual Remision Remision { get; set; }
    }
}
