//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remision
    {
        public Remision()
        {
            this.RemisionServicos = new HashSet<RemisionServicos>();
            this.OrdenServicio = new HashSet<OrdenServicio>();
            this.Factura = new HashSet<Factura>();
        }
    
        public int NumeroRemision { get; set; }
        public string CcNit { get; set; }
        public System.DateTime FechaRemision { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string Observaciones { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<double> Iva { get; set; }
        public string Usuario { get; set; }
    
        public virtual ICollection<RemisionServicos> RemisionServicos { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<OrdenServicio> OrdenServicio { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
