//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemisionServicos
    {
        public int IdRemisionServicios { get; set; }
        public int NumeroRemision { get; set; }
        public int Item { get; set; }
        public int Cantidad { get; set; }
        public double ValorUnitario { get; set; }
        public double ValorTotal { get; set; }
        public string Nombre { get; set; }
    
        public virtual Remision Remision { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
