//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaMora
    {
        public Nullable<int> NumeroFactura { get; set; }
        public string Cedula { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Total { get; set; }
    }
}
